# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Workflow syntax reference:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: PR Build

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # This is used by the SharedProps to detect a PR build
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node Modules
        run: npm ci

      # - name: Install CDK Node Modules
      #   working-directory: cdk/
      #   run: npm ci

      # - name: Build CDK TypeScript
      #   working-directory: cdk/
      #   run: |
      #     npm run build --if-present
    
      # - name: Run CDK Lint
      #   working-directory: cdk/
      #   run: npm run lint

      # - name: Run Tests
      #   run: |
      #     npm run test

      - name: Build Serverless Next.js
        run: |
          npx serverless

      - name: Build Story Book
        run: |
          npm run build-storybook

      - name: Smoke Check CDK
        run: npx cdk list

      - name: microapps-publish Smoke Check
        run: |
          npx microapps-publish --help

      - name: Deploy CDK Stack
        run: npx cdk deploy --require-approval never app
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
